### ISSUE TITLE
OctaveCoder not listed on the octave package index

### ISSUE THREAD

**Issue by tpapastylianou** [shsajjadi/OctaveCoder#15]
Dear OctaveCoder maintainer(s),

I noticed your package does not appear on the octave package index. If you feel your package is mature and stable enough to be included, then please consider submitting it!

Ideally, packages should be provided in the octave package format, such that they could be installed via octave's pkg command; however, this is not a strict requirement, and packages with custom installation instructions are also accepted on the index, as long as they provide clear installation instructions. :)

You can find the octave package index and instructions on how to add your package here: https://gnu-octave.github.io/packages/

**Comment by shsajjadi** [comment]
Dear Tasos Papastylianou,
Thanks for introducing the package index! Octave Coder, in my opinion, currently is  reasonably in a mature and stable state but its maintenance can be more difficult than other packages. Each new Octave version comes with bringing new features and fixes and removal of some internal functionalities that Coder depends on/should implement them. Therefore there may be a delay between the release of an Octave version and the release of the compatible Coder version.  So I'm afraid I can not follow in their footsteps and users encounter with an outdated package link.  However we should be optimistic about the future and try to improve the current situation! 
I will try to add the package to the index.

**Comment by tpapastylianou** [comment]
Thanks for the reply! I should clarify I'm not formally affiliated with the project; I'm simply a very happy octave user :slightly_smiling_face: 

But it has been my experience that package developers were generally unaware of the package index; I've pointed this out to a few developers so far, and they've been mostly excited to list their package on the index, so I have made a habit of pointing it out to the developers whenever I come across good packages.

But, to address your concerns, as I understand it, listing your package on the package index does not in any way bind you to some formal contract of up-to-dateness, any more than python packages on pypi or julia packages on pkg.julialang. It just helps octave users be more aware of its existence and of the larger ecosystem. From that point on it would be up to you (and perfectly acceptable) to dictate your own installation process, dependencies, compatible octave versions, etc.

<sub>Footnote: there is a separate discussion of 'core' packages, which are those that get bundled with the windows version for convenience, and are generally packages that mimic matlab toolboxes, which is a bit of a controversial topic in itself, since in theory packages are not officially affiliated with / maintained by the core octave project ... obviously I recognise the package you've created mimics the equivalent Matlab Coder one in terms of name and functionality, so you might want to speak more closely with the core octave developers if you think that's a good addition to the list of 'core' packages ... but I think the octave maintainers are generally trying to get away from the idea of 'core' packages anyway, and re-inforce the fact that packages are simply community offers, complementing the main octave project, in the same vein as what pypi is to python, etc. See https://octave.discourse.group/t/inclusion-of-non-traditionally-packaged-octave-packages-to-the-package-extension-index/1068 if you're interested in that discussion :slightly_smiling_face: </sub>

**Comment by siko1056** [comment]
Thanks for your great package @shsajjadi :slightly_smiling_face:

As suggested by @tpapastylianou , I took the freedom to list your great package there:

https://gnu-octave.github.io/packages/coder

If you feel unhappy about anything I or you can edit the entry at any time <https://github.com/gnu-octave/packages/blob/main/packages/coder.yaml>.

**Comment by shsajjadi** [comment]
Wow! Thank you @siko1056 for including the package in the list!
There are bug fixes some of them are related to Octave version 7 including the yesterday [commits](https://github.com/gnu-octave/octave/commit/ae1c4e6e4e321e3b379b017debc26de8f74accc7) that I hope to be prepared ASAP.  As discussed in Octave bug tracker there is a decision to restrict symbol visibility that may prohibit the development of packages like coder. However your encouragements give me the energy to continue the development until that decision is implemented.
Thanks again!
