### ISSUE TITLE
installer doesn't recognize version 5.2.1

### ISSUE THREAD

**Issue by arb1961** [shsajjadi/OctaveCoder#2]
Hi,

I happen to have checked out the latest on the 5.2 branch which is identical to 5.2.0, but has tag 5.2.1. The installer should accept that?

best

octave:2> pkg install -verbose OctaveCoder-coder-5.2.1.tar.gz
mkdir (/tmp/oct-0cNKNm)
untar (OctaveCoder-coder-5.2.1.tar.gz, /tmp/oct-0cNKNm)
error: the following dependencies were unsatisfied:
   coder needs octave == 5.2.0
stopped in /install_path/share/octave/5.2.1/m/pkg/private/install.m at line 180
180:       error ("the following dependencies were unsatisfied:\n  %s", error_text);

**Comment by shsajjadi** [comment]
Hi, @arb1961
I pushed some bug fixes and changed version numbers. Please download new releases.
Thanks.
