### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by diwadwar** [shsajjadi/OctaveCoder#20]
Hi, I've got a problem during installation of Octave Coder 1.8.0 on Octave 8.2.0.
Here's my error code:
```
pkg install "https://github.com/shsajjadi/OctaveCoder/archive/refs/tags/coder-1.8.0.tar.gz"
Installing package coder. It may take a while. Please wait ...
g++: warning: Files\GNUOCT1\OCTAVE2.0\mingw64/include: linker input file unused because linking not done
g++: error: Files\GNUOCT1\OCTAVE2.0\mingw64/include: linker input file not found: No such file or directory
error: mkoctfile: building exited with failure status
error: called from
mkoctfile at line 236 column 7
pre_install at line 25 column 5
install>prepare_installation at line 377 column 7
install at line 201 column 7
pkg at line 619 column 9
```

Do you know how to solve this?

**Comment by shsajjadi** [comment]
Hi,
I cannot reproduce the issue on a Windows system.
What is your OS and how did you install Octave?

**Comment by diwadwar** [comment]
Thanks for your reply. My system is Window 10 and I installed Octave from this website: https://octave.org/download#ms-windows, file octave-8.2.0-w64-installer.exe. However, it may be something wrong with my laptop. I tried installing the Coder on another laptop (the same system and the same Octave version) and it works. Therefore, I think we can close this topic. But if you accidentally reproduce this error, please let me know.

**Comment by shsajjadi** [comment]
It may be related to non ASCII characters on the path where the Octave or the package is installed. It is my guess.
Thank you for reporting the issue!
